dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"

env:
    global:
      - PGPORT=5433

install:
  - pip install -r requirements.txt
addons:
  postgresql: "11"

services:
  - postgresql
  - mysql

before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - pip install codecov
  - export PIP_USE_MIRRORS=true

before_script:
  - psql -c "CREATE USER travis;" -U postgres
  - psql -c "CREATE DATABASE test_crax;" -U postgres
  - mysql -e "CREATE DATABASE test_crax;"


script:
    bash launch_tests.sh

after_success:
  - cd tests
  - codecov
